---
bibliography: references.bib
format: 
  pdf:
    number-sections: false
    pdf-engine: lualatex
header-includes:
  - \usepackage{hyperref}
  - \newcommand{\hypref}[1]{\hyperref[#1]{\ref{#1}}}
  - \hypersetup{
      colorlinks=true,
      linkcolor=blue,
      filecolor=magenta,
      urlcolor=cyan,
      pdftitle={Pre Analysis Plan for Spatial Explicit Economic Values of Natural Capital in Europe},
      pdfpagemode=FullScreen
    }
editor: 
  markdown: 
    wrap: sentence
---

\title{Pre Analysis Plan for Spatial Explicit Economic Values of Natural Capital in Europe}

\author{
Julian Sagebiel, Nino Cavallaro, Maximilian Föhl, Martin Quaas,\\
Aletta Bonn, Maria Schnabel, Marie Meemken, Kevin Rozario, \\
Deutsches Zentrum für integrative Biodiversitätsforschung (iDiv) \\
Halle-Jena-Leipzig; Stefan Baumgärtner, Albert-Ludwigs-Universität \\
Freiburg (ALU); Moritz Drupp, Björn Bos, Pier Basaglia, Simon Disque, \\
Jonas Grunau, Universität Hamburg (UHH); Britta Tietjen, Fanny \\
Langerwisch, Freie Universität Berlin (FU); Harry Gölz, Beyhan Ekinci, \\
Veronika Liebelt, Bundesamt für Naturschutz (BfN); Björn Bünger, \\
Astrid Matthey, Jan Philipp Schägner, Umweltbundesamt (UBA); \\
Burkhard Schweppe-Kraft; Katarzyna Skrzypek, Katarzyna Zagórska \\
(University of Warsaw)
}

\maketitle

\begin{abstract}
\vspace{-0.5cm}
Abstract: Despite the urgent need to preserve natural capital, little is known about the direct benefits people receive from it. To achieve the UN sustainable development goals, especially Goal 15: Life on Land, reliable benefit estimates are required to incorporate the value of natural capital in national capital accounting, cost-benefit analyses, project appraisal, and in international policy agreements. What is needed is a comprehensive, transferable, and spatially-consistent benefit estimation. However, the multiple, interlinked services produced from natural capital make it hard to estimate its benefits, explaining a lack of robust benefit estimates. Using a novel valuation approach, the study discloses the benefits of natural capital and biodiversity, spatially differentiated all over Europe. The study employs a spatial-explicit choice experiment approach, which estimates benefits people receive from natural capital conditional on the current status in their places of residence. The results are easily transferable to other regions and contexts and allow trading off the benefits and costs of restoring natural capital and biodiversity. It can be seen in which regions the loss of natural capital is critical and where measures are most effective. Aggregated values indicate the overall willingness to pay of European citizens to restore natural capital, for example by adopting sustainable agriculture or creating natural protected areas. Stakeholders who are interested in the value of natural capital and biodiversity can easily use and adapt the estimates for their purposes. The results enrich the discussion on the loss of natural capital and biodiversity and can significantly contribute to broader policy discussions in the context of the interlinked climate and biodiversity crises.
\end{abstract}

# Part A: General Information {.unnumbered}

## Background {.unnumbered}

Economic values of natural capital are useful for policy makers at different scales and for different purposes.
Its importance is manifested in several international efforts guiding how to estimate such values[^1], and how to use thus values in various contexts[^2]. Uses of economic values of natural capital in policy making include welfare analyses, assessment of damages, cost-benefit analyses, stakeholder engagements and natural capital accounting. While there is a large theoretical and empirical literature on valuation of natural capital, we still lack a holistic and consistent set of values of natural capital. This study aims to provide values of natural capital, which benefit the overall aim of a holistic valuation. Specifically, we derive spatially-explicit high resolution economic values of natural capital. Using different valuation methods – choice experiments, life satisfaction, travel cost – we conduct a survey with spatially individual valuation tasks to estimate functions for values of protected natural areas and high nature value farmland. Regarding the choice experiment, we have developed a new method to incorporate the current endowment of natural capital in the valuation task. Survey participants are confronted with maps showing their current endowment and then make a choice between different policy scenarios. The current endowment is calculated using European-wide GIS data on protected natural areas and high nature value farmland.

[^1]: see for example The Economics of Ecosystem Services and Biodiversity - TEEB [https://teebweb.org/](https://teebweb.org/) or The International Panel on Biodiversity and Ecosystem Services - IPBES [www.ipbes.net/the-values-assessment](www.ipbes.net/the-values-assessment)

[^2]: see for example The System of Environmental-Economic Accounting SEEA [https://seea.un.org/](https://seea.un.org/)

Our approach allows us to derive high resolution maps with values all over Europe.
In our study, we present a novel approach in which high-resolution data from geographic information systems (GIS) are used directly in a discrete choice experiment.
We show respondents their status quo endowments with protected areas and high nature value farmland as well as proposed extensions to these areas on interactive maps.
Using an R algorithm and land cover data we ensure that all proposed changes are feasible.
With this unique technical feature of the discrete choice experiment, we enable the respondents to incorporate their endowment with natural capital around their place of residence in the decision process and ensure that all proposed landscape changes are feasible, visible, and relevant in distance to the respondents.
Further, we vary the accessibility of newly created protected areas, the visibility of the new high nature value farmland areas, and the distances to both of these new areas to partly disentangle the use and non-use values of these forms of natural capital.
Additionally, by incorporating socio-demographic and spatially explicit variables, we seek to identify how different populations and regions perceive substitutes and complements to natural capital.
The sample size of N = 15, 000 allows us to conduct an in-depth analysis of the major drivers in heterogeneity for preferences of natural capital.

## Key research questions {.unnumbered}

Our study contributes to the research on valuing natural capital, leading to two sets of different research questions.
First, we want to investigate the spatially-differentiated value of natural capital in Europe leading to the following set of research questions:

-    *What is the value of protected natural areas and high nature value farmland, and how does it differ across regions?*

-    *What are determinants (socio-demographics, landscape features, substitutes and complements of natural capital) of these values?*

-    *To what extent does the distance of natural capital impact its marginal value and welfare estimates?*

-    *To what extent do spatial endowments of protected areas and high nature value farmland affect its marginal value and welfare estimates?*

-    *What differences emerge between use-related values and non-use-related values?*

-    *To what extent are values transferable between regions and how can the transfer function be optimized?*

Second, we want to investigate several methodical questions, inherent to the current practice of choice experiments and the travel cost method:

-   *What are the implications of the usage of different specifications of the utility function (e.g. linear, quadratic, Box-Cox) on welfare estimates?*

-   *Does the scope (i.e. regional extent) of a measure to protect natural capital impact the value (scope and embedding effects)?*

-   *Are elicited values constant over different methods (choice experiment, travel cost method, life satisfaction)?*

-   *How do the distributional consequences of the payment vehicle impact choices and values?*

-   *How do different time horizons of the payment period impact choices and values?*

-   *In the context of recreation demand (travel cost) approach, how does survey formulation influence the respondent’s answers, and can targeted survey tools (e.g., interactive maps, timeline graph, calculation hints, feedback on reported numbers) improve recall and affect the obtained welfare estimates?*

## Hypotheses \label{Hypotheses} {.unnumbered}

### General hypotheses:

\newcounter{hyp} 
\setcounter{hyp}{0}

-   **Hypothesis** \refstepcounter{hyp}\thehyp \label{hyp-1}: People are willing to give up some of their income to improve natural capital in the form of protected areas and high nature value farmlands.

-   **Hypothesis** \refstepcounter{hyp}\thehyp \label{hyp-2}: The value of natural capital is significantly influenced by sociodemographic characteristics and spatially explicit factors, leading to variations in values across different groups and regions.

-   **Hypothesis** \refstepcounter{hyp}\thehyp \label{hyp-3}: The marginal value of natural capital decreases as endowment increases, suggesting diminishing returns.

-   **Hypothesis** \refstepcounter{hyp}\thehyp \label{hyp-dist}: The marginal value of natural capital decreases as distance to it increases, and this effect is even more pronounced if the change in natural capital is related to use-values.

-   **Hypothesis** \refstepcounter{hyp}\thehyp \label{hyp-4}: Use related values of natural capital are higher than non-use related values.

-   **Hypothesis** \refstepcounter{hyp}\thehyp \label{hyp-5}: With a well specified transfer function, values can be reliably transfered between regions.


### Methodological hypotheses - Choice Experiment

-   **Hypothesis M1** \refstepcounter{hyp}\thehyp \label{hyp-M1}: The scope of the changes in natural capital is influencing the values of natural capital.

-   **Hypothesis M2** \label{hyp-M2}: The distributional consequences of the payment vehicle have a significant impact on the elicited values of natural capital.

-   **Hypothesis M3**\label{hyp-M3}: Derived natural capital values depend more on the relative than the absolute attribute levels, when comparing two different vectors of attribute levels.

-   **Hypothesis M4**\label{hyp-M4}: If the duration of the payment period increases, respondents are less likely to vote in favor of increases in natural capital.


### Methodological hypotheses - Travel cost study

\setcounter{hyp}{0}

-   **Hypothesis T0**\label{hyp-recall}: For recreation demand (travel cost) approaches, utilization of recall-targeted survey tools (i.e., interactive maps, timeline graph, hints for rule-based calculations and feedback on reported numbers) have a significant impact on the reported number of visits and their characteristics as well as on the resulting welfare estimates.

-   **Hypothesis T1**\label{hyp-map}: Provision of an interactive map at the beginning of the travel cost study part affects the location of the most frequently visited environmental site the respondents describe (e.g. distance from the place of residence) compared to provision of a map at the end of the travel cost study part.

-   **Hypothesis T2**\label{hyp-map2}: Provision of an interactive map at the beginning of the travel cost study part and subsequent display of selected location on the map in trip-number and trip-information elicitation questions compared to provision of a map at the end of the travel cost study part:

    \begin{itemize}
    \item T2.1\label{hyp-T2.1.}  Affects the reported number of trips (e.g. mean and distribution).
    \item T2.2\label{hyp-T2.2.}  Affects the visit information reported by the respondents (e.g. site type, whether they make the visits with their dog, number of people accompanying them, duration of time spent at the visited location).
    \item T2.3\label{hyp-T2.3.}  Affects the mechanism used for trip number information retrieval.
    \item T2.4\label{hyp-T2.4.}  Affects the resulting welfare measures.
    \end{itemize}

-   **Hypothesis T3**\label{hyp-T3}: Provision of hints for rule-based calculations of past trips compared to no hints:

    \begin{itemize}
    \item T3.1\label{hyp-T3.1.}  Affects the reported number of visits (e.g. mean and distribution).
    \item T3.2\label{hyp-T3.2.}  Affects the resulting welfare measures.
    \item T3.3\label{hyp-T3.3.}  Affects the mechanism used for trip number information retrieval.
    \item T3.4\label{hyp-T3.4.}  Affects the probability of respondents readjusting their reported number of trips when asked whether the number is correct.
    \end{itemize}

-   **Hypothesis T4**\label{hyp-T4}: Provision of the timeline graph in the visit number elicitation question compared to no timeline graph:

    \begin{itemize}
    \item T4.1\label{hyp-T4.1.}  Affects the reported number of visits (e.g. mean and distribution).
    \item T4.2\label{hyp-T4.2.}  Affects the resulting welfare measures.
    \item T4.3\label{hyp-T4.3.}  Affects the mechanism used for trip number information retrieval.
    \item T4.4\label{hyp-T4.4.}  Affects the probability of respondents readjusting their reported number of trips when asked whether the number is correct.
    \end{itemize}

-   **Hypothesis T5**\label{hyp-T5}: Provision of feedback on how the reported number of trips translates to average frequency of visits before asking the respondents




## Publication strategy

*The large dataset cannot be summarized and analyzed in one single paper. For different research questions, we plan to write different papers. Despite our efforts to attain a clear-cut publication strategy, we note that some of the papers may turn out to not be feasable, while other paper ideas may emerge after the study has been conducted. Acknowledging the benefits of pre-registrations, we will not commit to the pre-registered papers only and leave room for new paper ideas. Among other things, this is due to the fact that more than 20 researchers from various scientific fields were involved in the survey and that in some disciplinces pre-registration is not common practice. The following list contains all papers we are currently planning to write.*

\newcounter{paper} 
\setcounter{paper}{0}

\refstepcounter{paper}\thepaper.
Spatial explicit valuation of natural capital in Germany and its transferability: Implications for policy and benefit transfers 

-   The paper serves as the main paper to analyze the choice experiment data of the survey.
-   We estimate a spatial explicit utility function to capture local willingness to pay values for landscape changes.
-   We derive a marginal willingness to pay function that contains spatial and socio-demographic variables. The willingness to pay function allows us to predict marginal willingness to pay on high resolution spatial units. 
-   Having a large set of observed values, we test how the marginal willingness to pay function predicts local marginal willingness to pay. 
-   We use several different utility specifications (quadratic, logarithmic, Cox-Box) and different predictor variables to empirically identify the best specification in terms of a) model fit and b) predictive power.
- Related to Hypotheses \hypref{hyp-1} , \hypref{hyp-2}, \hypref{hyp-3}, \hypref{hyp-4}, \hypref{hyp-5}


\refstepcounter{paper}\thepaper.
The effect of scope and distance on stated preferences

-   The literature has impressively shown a lack of sensitivity to scope of stated preferences, while distance to the good to be valued plays a critically role in explain stated preferences. 
-   This paper investigates the effects of distance and scope simultaneously in a between-sample and within sample experiment. 
-   Scope is defined as the actual amount of the good to be valued, while distance is defined as the distance to the good to be valued as well as the quantity within distance.
-  Relates to Hypotheses \hypref{hyp-3}, \hypref{hyp-dist} \hypref{hyp-M1}, \hypref{hyp-M3} 

\refstepcounter{paper}\thepaper.
Estimating the economic value of recreation in natural environments using travel costs

-  The paper analyses the travel cost part of the survey and investigates the methodical research questions related to travel cost.

-  Relates to Hypotheses \hypref{hyp-recall} to \hypref{hyp-T5}

\refstepcounter{paper}\thepaper.
The impact of nature relatedness (NR) and health/wellbeing on the economic value of natural capital

-	 In this interdisciplinary article, we analyse the interplay between psychological variables and the willingness to pay for natural goods and services. We estimate a structural equation model explaining the relationships between NR using a scale developed by @Nisbet2013, WTP and health/wellbeing. 
-  The goal is to identify society characteristics that are relevant for the success of, and willingness to pay for nature conservation efforts.
- 	People with high NR derive higher utility from nature conservation efforts and are thus more likely to exhibit higher WTP in our study.
-	 Higher NR predicts better psychological and physical wellbeing. Possible pathways for this effect include increased physical activity outdoors, stress reduction and attention restoration as well as the promotion of social interactions.
-	 Higher wellbeing is associated with higher WTP for nature conservation. Mechanisms might be a higher utility from protection efforts, which has been shown in consumer behaviour in reaction to carbon labelling on products. Another pathway might be a subjective feeling of job security, based on good health, leading to a higher willingness to commit to the burden of  longer-term investments.
-	 The relationship between NR and WTP is moderated by higher wellbeing, while the relationship between wellbeing and WTP is moderated by NR.
-	 SES/Income effects WTP and Wellbeing, while NR is unaffected by it.


\refstepcounter{paper}\thepaper.
Left-right bias and ordering effects in choice experiments

-   Several papers have shown that the order of attributes and alternative affect choices in a stated preference survey.

- We investigate this issue by making use of different split samples that varied the order of alternatives and the order of attributes.

- We analyze the data using non-parametric tests of choices based on the split samples

- We compare willingness to pay between the split samples using separate conditional logit and mixed logit models for each split sample and joint conditional and mixed mixed logit models with interactions between attributes and split samples.

\refstepcounter{paper}\thepaper.
Life satisfaction and Natural Capital

- We investigate how stated life satisfaction and perceived mental and physical health is related to the endowment of natural capital. 

- We use the amount of natural protected areas in the proximite area of the respondent and the share of high nature value farmland on agricultural land as our main proxis for natural capital.

- We use more spatial variables including distances and socio-demographic variables to explain life satisfaction.

- We estimate willingness to pay by dividing the coefficient of our natural capital proxy by the coefficient of the respondents (logged) income.

- We use measures of fit to identify the best model fit.

\refstepcounter{paper}\thepaper.
Comparison of methods to estimate the implicit price of natural capital: Choice experiments, travel cost and life satisfaction

- Based on the results from the three valuation approaches in this survey, we compare welfare measures derived by these approaches. 

- We derive a theoretical model that can be used by the three approaches similarly to derive welfare measures.

- Theoretically, we would expect similar results, but this has often not be the case in the empirical literature. 

\refstepcounter{paper}\thepaper.
The effect of the distribution of costs on willingness to pay for natural capital

-   Despite the fact that people are willing to give up income in exchange for a better natural environment, several people state not to pay conditional on the actual distribution of the costs. -  Costs can be distributed in various ways. Richer people can be asked to pay more than poorer people, everyone can pay the same, those who benefit most can pay more, and those who create more damage pay more. 

-  This paper explores the acceptance of an individual payment for improvements on natural capital conditional on how the costs are distributed. 

-  We set up a theoretical model that models rejection of a specific payment as an argument in the utility function.

\refstepcounter{paper}\thepaper.
Germany's biodiversity valued at market prices

-   Biodiversity is conceptualized in the form of biotope value points. The paper delves into the markets for biodiversity, examining how transaction prices relate to subjective willingness to pay and welfare considerations. 

-  We therefore combine price estimates per biotope value point obtained from an expert survey of the ValuGaps research project with estimates from the survey described hereafter. 

-  The goal of the research is to translate biotope valuation methods into the standardized framework of Germany's Federal Compensation Ordinance in order to make an intent at assessing the overall value of German biotopes and habitats at market prices. 

-  The findings inform environmental economic accounting, policy scenario development, project planning, life cycle assessments, and corporate natural capital assessments. The paper also evaluates the methodology's potential for application beyond Germany, suggesting its broader relevance and utility in biodiversity valuation globally.

# Part B: The survey in detail {.unnumbered}

## Data and Experimental Setup \label{data-exp-setup}

The survey sampling was conducted through the survey company SurveyEngine. The sample is a probabilistic sample of the adult population in Germany with representative quotas for age and gender, and additional soft quotas for income and region. The main quotas are replicated within the split samples. We aim for a sample size of N = 15,000. SurveyEngine collaborated with panel companies to recruit the respondents. The sample comes from different panels from market research institutes in Germany. SurveyEngine billed us around €5 for each survey participant counted as complete. The exact remuneration the respondents varied. Upon request, SurveyEngine informed us that these panel companies do not disclose the exact pay-out to the respondents, as it would partly reveal their internal cost structure. Furthermore, the actual pay-out made to respondents is dynamic, as are the internal costs, both of which are a function of factors determined by each panel. The method of payment also varies, as some panels pay respondents directly, while others offer vouchers or reward points that can be accumulated.

 As the survey was financed by a research project, we tried to maximize the sample size for the given project budget which allowed us for a total sample of N = 15,000. For the choice experiment, we used simulations to test whether statistical design can deliver unbiased estimates. We used simple discrete choice conditional logit model with a specification assumed from earlier studies [@Sagebiel2017]. The results of the simulation are in the appendix and the code (in R) is available on github.

We note that not all parts in the survey benefit from the full sample. As we describe more thoroughly in subsections \textbf{\hyperref[subsec-que-structure]{Questionnaire: Structure}} and \textbf{\hyperref[split-samples]{Split Samples for Between-Subject experiments}}, some survey parts are not shown to all respondents. For example, the travel cost method is only shown to 10,000 respondents while the behavioural experiment is shown to the remaining 5,000 respondents.


## Questionnaire: Development \label{subsec-que-dev}

The questionnaire was developed together with an inter- and transdisciplinary team of experts on biodiversity from ecology, social sciences and economics. Two German federal agencies  were actively involved in the development of the German version of the questionnaire: The German Federal Agency for Nature Conservation (BfN) and the German Environmental Protection Agency (UBA). Additionally, we incorporated feedback from the German Federal Statistical Office into our study set-up. Lastly, Katarzyna Skrzypek of University Warsaw was responsible for the set-up of the travel cost section.

The questionnaire was tested in an iterative process across different stages of development. The development of the choice experiment was accompanied by ten focus groups with 60 participants and adapted according to the outcomes of the focus groups. In addition to the focus groups, we conducted two rounds of pilot studies with a near-final version of the survey were conducted with a total of 400 participants. The structure and results of the focus groups and pilot studies are described in more detail in the subsequent subsections.\newline

**Focus groups**\
We grouped the focus group participants according to two distinct criteria: their place of residence and their educational background. We distinguished between those living in urban and rural areas and whether a participant had a university degree or not. Each group consisted of between four and nine people and each session lasted 90 minutes. In order to facilitate the adaptation of the questionnaire to the specific content of each group, the focus groups were conducted in three separate waves, with each wave targeting a different focus area. In the first and second waves, we held four groups each, in order to have one group for each intersection of living area and educational background considered.

-   The first wave was based on testing the general presentation of content and concepts. The participants discussed the voice of tone, the illustrations, the policy scenario, and the map feature. The payment vehicle and the hypothetical political process presented the main discussion points.

-   In the second wave, the reduced introductory information and the updated policy scenario were evaluated in terms of their adequacy and accessibility. The discussions focused primarily on the map feature and the choice cards, providing insights into how participants approach and address the elements of the choice experiment.

-   In the third wave, we conducted two final groups, one consisting of participants living in a rural area and the other in an urban area. Participants independently completed a maturity level version of the questionnaire and provided feedback at intermediate stages. The comments on aspects such as mobile readiness, illustrations and decision-making in choice experiments proved valuable for the subsequent layout redesign we carried out with a contracted design agency.\newline
\

**The pilots (pre-tests)**\
Prior to the actual launch of the survey, we conducted two pre-tests with 200 respondents per pre-test in August and October 2024. Both were conducted with a pause in recruitment after the first 50 respondents to allow for adjustments if major structural problems were identified. One of the main interests for the pre-tests was to check the functionality of the survey. After conducting the necessary checks, we were able to rule out any major glitches hindered participants from completing. We were able to ensure that neither consent to data collection nor technical problems would cause participants to drop out in large numbers at once. 

As a part of this, we examined whether the type of device had an impact on the drop-out rates. Specifically, we identified beforehand the length of the questionnaire, the amount of content and the technical requirements as potential causes of mass dropout at various stages. We therefore paid particular attention to potentially heterogeneous dropout rates for users of specific devices or operating systems. In fact, we observed that about 12% (65 out of 534 active participants) dropped out at the first choice card, and all were using a mobile device as opposed to a computer. The data suggests that a large number of them were using an old version of Android that was incapable of properly loading the leaflet maps required at this point. Given our approach to implementing spatially relevant choice experiments with individualized choice maps, we naturally face a trade-off between technically sophisticated and detailed presentation of the good and technical accessibility. Although we might see higher dropout rates at this point, we chose not to screen out these versions initially. Instead, we opted for a modified invitation message that nudges respondents to open the survey on their computer in the first place.

The initial pre-test indicated that the data collected with the levels of area extension of high nature farmland and protected areas in place may not fully capture the impact of these variables on the overall approval of a proposed landscape modification.  To address this issue, an additional split was introduced in the sample, with one half of the respondents presented with potential landscape modifications of the original aggregated area size and the other with levels that are twice as high. The randomizations that had already been implemented were confirmed to have achieved the desired outcome of a balanced distribution of participants across all splits. The statistical independence of these categorical variables was tested using a Chi-squared test. 

We also included an open question in the survey, enabling respondents to provide direct feedback on their decision-making processes in the choice sets. This optional question was presented to respondents after they had completed all ten choice sets. A similar number of responses indicated that personal factors, such as the current state of their immediate surroundings or general support for nature protection, influenced their decisions, as those that mentioned organisational factors, such as the payment method, public decision-making, and unintended side effects. The largest part of responses listed the attributes of cost, area size, accessibility and visibility, and proximity as the determining factors in the decision-making process. Of these, approximately half of the respondents indicated that they primarily considered the cost or a cost/benefit trade-off. \newline

**Soft launch**\
For the final data collection we started the survey with a soft launch with a sample size of N = 1000 to test whether all changes made after the two rounds of pretests have been implemented correctly. In this process we discovered a coding mistake in our R code used to calculate the status quo endowments of the respondents. Specifically, we had a mistake in the way how we calculated the amount of protected areas which resulted in lower than actual values for the endowment with protected areas, particular in regions with many small patches of protected areas. We changed the R code accordingly for the rest of the data collection. Further, we found a coding issue in the setup of the split sample for the equity treatments which we also corrected.
The data from the soft launch will not be used for the main analyses, but used for robustness checks. 

## Questionnaire: Structure \label{subsec-que-structure}
 
The survey is divided into six progressively structured sections, using simplified language and a user-friendly design. To enhance information absorption, we reduced the content on each screen and included bullet points and infoboxes where feasible. Graphical illustrations are used to explain key concepts, while images and examples aim to reflect regional diversity in order to improve understanding and relevance for a broader audience. Presenting additional information in the form of foldable text elements allows interested respondents to clarify unresolved questions about concepts and content, while allowing others to move on more quickly. In this way, we aim to reduce drop-out rates due to time constraints and to provide a supportive environment for those who demand additional information.


The core of the valuation study is a discrete choice experiment. A choice experiment is a commonly used, yet highly contested, method in environmental economic valuation. A large literature discusses its validity and provides best practices and conditions for valid preference elicitation and welfare measurement. One purpose of this pre-analysis plan is that we want to make sure that we have accounted for all necessary conditions and already discuss potential challenges regarding validity before data collection. The choice experiment is complemented with two other economic valuation approaches – travel cost method and life satisfaction. These approaches are based on the same theoretical framework as choice experiments and should - in theory - provide similar results. A comparison of the results of the three methods allows us to investigate the validity of our value estimates. \newline

**Introduction and first questions**\
The first part presents the core topic of the survey and the personal information that is required from the survey respondents. Consent for the collection and processing of personal data as well as compliance with the population representation quota of the survey are required for inclusion. If participants do not meet these criteria or refuse to give consent, they will be screened out before reaching the first information block.\
The second part provides an introductory overview of the relationship between agricultural use and biodiversity. Illustrative sample images and text elements present the concepts of high nature value farmland and protected areas in an accessible and intelligible manner. The information elements are interrupted by content-related follow-up questions, in order to enhance reader engagement and attention.\newline

**Life satisfaction**\
To analyze the relationship between natural capital and life satisfaction we include a question about life satisfaction at the beginning of the survey, where we ask the respondents “Overall, how satisfied are you with your life right now?”. Respondents can answer on a scale from 0 to 10 and also have the option to not answer the question. Additionally we ask questions about physical and mental health of the respondents on the next page. Together with the information from the other socio-demographic questions we are able to run regressions of life satisfaction on socio-demographic and natural capital variables. Using this regression results we can calculate an income equivalent change in natural capital while keeping life satisfaction constant, which can be interpreted as the willingness to pay for natural capital changes.\newline

**Choice Experiment**\
The third part of the survey introduces respondents to key attributes of the upcoming choice experiment. This section outlines potential landscape modifications, the financial framework, and the structure of the hypothetical political process involved in the proposed project as well as an interactive illustration of hectar sizes according to the proposed landscape changes.
The fourth part of the study consists of a discrete choice experiment in which participants are asked to choose between two options: the status quo or a proposed landscape modification. Each choice is accompanied by two interactive maps, illustrating the spatial distribution of the respective areas, and a choice table detailing relevant information. Participants must select their preferred option, and this process is repeated across ten consecutive pages, with each page presenting a unique proposal. The proposals are randomly selected per respondent from a full factorial of 1500 choice sets, and differ with respect to the area size and distribution of the planned extension of high nature value and protected areas, their visibility or accessibility, respectively, and the related mandatory annual payment.\newline 

**Follow-up questions**\
In the literature on stated preference studies, respondents who categorically reject the hypothetical scenario presented despite they actually benefit from the scenario (willingness to pay > 0) are referred as protesters. The decisions of these protesters are likely to be driven by motives other than the evaluation of the presented attributes of the choice sets. The correct identification of protesters is important because their inclusion or exclusion from the analysis can affect welfare estimates [@Strazzera2003]. In order to distinguish protesters from respondents whose decisions genuinely reflect their preferences, a threshold value of rejections has been implemented. If a respondent rejects at least seven of the ten proposed landscape modifications presented, they are redirected to answer a subset of questions on the subsequent page, after the final choice set, in order to elicit further information regarding their general opposition to the project presented. These five questions ask about their general views on the payment instrument, whether they felt there was a lack of information, or whether they objected to the way the questions were posed. The questions are used to classify the respondents into protesters and “true WTP <= zero” respondents. After this page, these respondents continue with the questionnaire. On the next page, all respondents receive the same follow-up questions about the general underlying motivations behind their choices in the choice experiment.

This follow-up page consists of a series of matrix questions to be answered on a 5-point Likert scale. The questions are designed to elicit information about the respondents' general attitudes and considerations regarding the consequentiality of the survey. Respondents are then asked for their opinion on the distribution of costs between households. At the end of this part of the survey, we ask the respondents in a non-obligatory open question for any general comments on their response behavior in the previous sets of choices. The responses we collect at this point can complement the interpretation of the choice experiment data and potentially form the basis of independent qualitative research.

Taking the data from the soft-launch sample, 98[^3] out of 147 comments were related to the content of the survey. The predominant self-reported drivers for voting for or against a proposed landscape change can be categorized into three groups: The presented attributes, the organisational aspects and the respondents' general personal views on nature conservation:

[^3]: Responses that touched on two or three issues were assigned to each of these categories. For this reason, the total does not add up to the sum of the individual categories.

-   Among the survey attributes the most frequently mentioned was cost (32), as suggested by preliminary data analysis of the choice experiment data from the soft launch sample. Respondents cited either the overall cost as critical, the cost in relation to the budget constraints they face, or in terms of a cost/benefit trade-off. Sixteen comments mentioned the size and dispersion of the areas to be created, the latter including the proximity of the areas to their homes. Accessibility or visibility played only a minor role.

-   With regard to the organizational aspects, twenty-two respondents firmly opposed any additional taxes or levies, often accompanied by the statement that the current tax burden on individuals is already high enough and should be borne by the government. Another six responses alluded to a general distrust of politics. Another seven responses mentioned the treatments \textbf{\hyperref[split-samples]{duration of the payment period}} and \textbf{\hyperref[equity]{distribution of the payment}}.

-   Fourteen respondents explained their vote either by their personal relationship to nature, e.g. general support for biodiversity protection, or by pre-existing conditions around them, e.g. the status quo of nature in their region. In addition, eighteen responses made only general comments about personal support or opposition, of which only two were generally opposed to the project.  \newline

**NR6, CV, and Travel Cost**\
In the fifth part of the study, the participants are divided into two groups, which then receive different questions. Subsequently, one-third of the participants engage in an experiment examining distributional decisions between financial and environmental budget appropriation. The remaining two-thirds of participants are first required to complete the six-item questions of the Nature-Relatedness scale [@Nisbet2013]. The Nature Relatedness scale (NR6) is a 6-item self-report measure, allowing assessment of individual attitudes towards nature in the form of a “self” and “experience” scale. It is a short version of the original 21-item Nature Relatedness Scale. After the NR6 questions, respondents are asked to indicate their willingness to pay for a general programme that seeks to fulfil the EU biodiversity goals, using a contingent valuation question. At the conclusion of this section, participants are presented with questions regarding travel costs associated with their recreational visits to local environmental sites.  Between the pre-tests and the soft launch we extended the contents of the travel cost part and implemented four mutually independent treatments. The format of the questions in the travel cost study part will depend on the treatment group to which the respondent is assigned. The questions will inquire about the number of visits to local environmental sites and whether the interactive map is presented at the beginning and displayed on the following screens, or only at the end of the section. The four treatments are described in the \textbf{\hyperref[travel-cost]{travel cost}} subsection. Approximately 50% of respondents will be randomly assigned to each of the two groups within each treatment. This results in approximately 6.25% of respondents being exposed to each of the 16 possible combinations of the survey. \newline

**Socio-economic data**\
In the concluding section of the survey, respondents are presented with a series of conventional questions about their socio-economic circumstances, including educational background, employment status, household income, household size, current political party preference, and their living situation. Additionally, we ask respondents if they are private forest owners. If they are, we further ask them about the size of the private forest they own and how much wood they annually use from this forest.


## Randomizations \label{randoms}

The sequence of the response options may lead to a distortion of the observed results, due to phenomena such as primacy or recency bias. To address this issue, we implement randomization at various points in the survey.\newline

**Order of choice sets**\
Respondents were presented with 10 randomly drawn choice sets from the full factorial.\newline

**Order of alternatives**\
For one half of the respondents, the status quo is located on the left side of the screen, while the proposed project measures are located on the right side.
For the other half, the aforementioned information is presented in a reversed order.\newline

**Order of attributes**\
To avoid bias from the order of attributes in the choice sets, respondents are randomly assigned to one of four groups.
These groups determine the sequence of attributes displayed in the choice cards presented below the choice maps.
The sequences are as follows:

\begin{itemize}
    \item 1, 2, 3, 4, 5
    \item 3, 4, 1, 2, 5
    \item 5, 1, 2, 3, 4
    \item 5, 3, 4, 1, 2
    \end{itemize}

It should be noted that rotation of attributes occurs between subjects, i.e. each respondent has the same attribute order in all choice sets.
To further facilitate readability for the respondent, the attributes for HNV areas (3 and 4), namely size and visibility, and for protected areas (1 and 2), namely size and accessibility, are rotated only pairwise and maintain a consistent neighboring order across all four groups.
Attribute 5 is the yearly payment to the respondent and is always either shown first or last to ensure visibility of the cost attribute.\newline

**Multiple choice questions**\
We follow best practice by randomizing the order of questions within a matrix of questions.
This includes an attention check question, where the question asks respondents to select a particular option on a Likert scale.
Similarly, we randomize the order of answers for each question in single and multiply choice questions.

## Split Samples for Between-Subject Experiments \label{split-samples}

**Duration of the payment period**\
In order to examine whether the duration of the mandatory annual payment has an impact on the decision of citizens to approve a project, the entire sample was divided into four equal groups.
The four groups will be presented with a different payment duration in the questionnaire.
The durations under consideration are five years, ten years, twenty years, or that the mandatory payment remains in place indefinitely.
To ensure that survey participants do not overlook the information, we have included it at multiple points.
Firstly, on the page providing information on the referendum process, the payment period length is included in the infographic on the timeframe of the landscape modification project and also displayed at the bottom of the page, highlighted to ensure that it captures the reader’s attention.
Subsequently, the information is presented between the question and the answer options on each of the ten choice sets.
The objective is to ensure that respondents are aware of the temporal consequentiality of their decisions and to test whether respondents solely consider the amount of annual payments or whether the lifetime total influences their decision-making process.\newline

**Radius of potential extensions**\
Moreover, we incorporated a split for the radius surrounding the residence, within which the potential extensions of the discussed areas may occur.
The aforementioned levels are 15 km, 20 km, 25 km, and 30 km.
One motivation for the implementation of this split is that, in consideration of the attributes of accessibility and visibility, the radius may exert an effect insofar as the areas presented are not in the immediate distance reachable without the use of a motorized vehicle.
Furthermore, the radius displayed may influence respondents’ orientation to the map.
Areas may be less easily identifiable, particularly those that are more dispersed, and landmarks that are familiar to respondents may be more challenging to locate on a map that encompasses a larger area.\newline

**Size levels of area extension**\
We repeatedly remind respondents that each set of choices should be considered separately, and therefore only the attributes of each proposed landscape change compared to the status quo should be considered in their decision.
Nevertheless, as respondents answer the ten sets of choices, they become aware of the full range of potential expansions.
We account for the effect of the previous examples on the decision by randomizing the order in which they appear (see the \textbf{\hyperref[randoms]{Randomizations}} subsection for details).
The question remains as to how the participants perceive these area sizes:

1.  Respondents may base their choices on the relative size of the areas, using a comparative scale where the levels are relevant to them in relation to each other.
    This may be due to a lack of ability to conceptualize hectare sizes.

2.  Alternatively, respondents may base their choices on absolute area increases, considering actual changes in hectares and percentage points as relevant measures.

Another reason for implementing a split at this point is that we want to cover a wider range of potential landscape modification areas, without overwhelming the individual participant with too much variety within their choice sets.
\

**Distribution of payment** \   \label{equity}
Apart from having a direct willingness to pay for natural capital, people may also have preferences for the distribution of the burden between individuals or households.
Naturally, one would assume that people who have higher incomes should pay more.
Thus equity preferences may impact the voting in the choice experiment.
We develop two hypotheses regarding equity preferences:

1.  If all individuals or households pay the exact same absolute amount, some respondents perceive this as unfair and vote against despite having a willingness to pay for the proposed change.

2.  If individuals pay according to their income, some respondents are willing to pay more the proposed changes, as they perceive the payment as fair.

We implement a test for the hypotheses by adapting a split-sample approach. In one split sample, we tell respondents that all individuals pay the same absolute amount. In the second split sample we tell respondents that individuals pay according to their income in analogy to their marginal tax rate (Grenzsteuersatz). We do not provide specific details or examples as we expect that respondents are concerned about the idea that richer people pay higher amounts, while they do not consider the exact differences in payment. Such a heuristic was confirmed in the focus groups. As a manipulation check we ask respondents after the choice experiment how the burden was distributed. If respondents have read the text, they would be able to give the correct answer. Additionally, we ask respondents to state they preference for the distribution of the burden in a multiple choice question.
\

**Travel cost study** \   \label{travel-cost}
The travel cost study part of the survey employs a between-subject design comprising four treatments, which are randomly assigned and independently allocated to respondents. Each of the four treatments comprises two versions of the survey, resulting in 16 distinct iterations of the travel cost study part.
The description of versions of the surveys associated with each of the treatment groups is provided below: 

1.  Group 1A respondents are first presented with an interactive map on which they must pin the location of their most frequently visited environmental site. A series of questions then ask respondents to provide more detailed information about the site and their visits to it. On the top of these screens, respondents are presented with a non-interactive map displaying the location of the site they selected before.\
Group 1B respondents are first asked the full set of questions about their most visited environmental site. Only at the end of the TC section are they presented with an interactive map on a separate screen on which they can pin this site.

2.  Group 2A respondents are first presented with a timeline graph visualising the last 12 months and some key events to help recall the period being analysed. This timeline graph is displayed below the question asking them to indicate the number of visits to all local environmental sites and below the question about their visits to their most frequently visited site.\
Group 2B respondents will have no graph displayed below these questions.

3.  Group 3A respondents is provided with a calculation hint between the question and the input box to report the number of visits to all local environmental sites. The same applies to the question about their visits to their most visited site.\
Group 3B respondents  is not provided with such a calculation hint.

4.  Group 4A respondents will be presented with a conditional feedback script on the screen subsequent to their initial response regarding the number of visits. This provides respondents with the number of visits they have reported and translates it into both monthly and weekly frequency of visits over a 12-month period. To illustrate, respondents who have made 26 visits will be presented with the following text: "You indicated that you have made 26 visits to environmental sites in the last 12 months. This means you visited environmental sites approximately twice a month." Subsequently, respondents are asked to verify or adjust the total number.\
Group 4B respondents will only be presented with the number of visits from their initial response and invited to verify or adjust the total number.





## Exclusion criteria

Respondents are excluded according to the following criteria:

1. We use control questions in Likert scaled question blocks where respondents are instructed to select one specific answer. If respondents did not select this answer, it is likely that they did not read the question properly, and randomly clicked through the survey. Respondents who fail this “attention check” will be excluded

2. We follow the survey company's convention of considering any respondent who completes the survey in less than one-third of the median time will be classified as a "speeder." Given the results of our pilot studies, we expect this cut-off to be up to approximately 8.5 minutes.

3. We exclude duplicate respondents by checking equal IP addresses and socio-demographic characteristics. If several respondents have the same IP addresses as well as age and gender they are excluded and only the first observation is kept.



# A pre-registration template for Choice Experiments {.unnumbered}

To provide more specific information on the choice experiment, we adapt a template which has been used for example here https://osf.io/vc8hq and https://osf.io/gbjh6. As some of the questions in the template are already answered in the main text, we will refer to the relevant chapters.

\newcounter{que} 
\setcounter{que}{0}

-   **\refstepcounter{que}\theque.**\newline
    (/)

-   **\refstepcounter{que}\theque. What are your hypotheses?** \newline 
    (see the \textbf{\hyperref[Hypotheses]{Hypotheses}} subsection for details)

-   **\refstepcounter{que}\theque. What is the format of the survey instrument (eg.online, ftf, etc.)?** \newline
    The survey is carried out online by the survey company SurveyEngine. The collaboration with SurveyEngine covered all development stages of the survey, including all pilot studies.

-   **\refstepcounter{que}\theque. Motivate and describe your sampling approach. [Probabilistic sample, Convenience sample, stratified, clustered, quotas applied]** \newline
    (see the \textbf{\hyperref[data-exp-setup]{Data and Experimental Setup}} subsection for details)

-   **\refstepcounter{que}\theque. How did you incentivize your sample?** \newline
(see the \textbf{\hyperref[data-exp-setup]{Data and Experimental Setup}} subsection for details)


-   **\refstepcounter{que}\theque. How did you determine the sample size (e.g. power analysis)?** \newline 
    (see the \textbf{\hyperref[data-exp-setup]{Data and Experimental Setup}} subsection for details)

-   **\refstepcounter{que}\theque. Did you conduct any pre-studies to develop the DCE and questionnaire? Please describe the procedure.**\newline 
    (see the \textbf{\hyperref[subsec-que-dev]{Questionnaire: Development}} subsection for details)

-   **\refstepcounter{que}\theque. Anything else you want to mention regarding survey information:** \newline 
    (see the \textbf{\hyperref[subsec-que-structure]{Questionnaire: Structure}} subsection for details)

-   **\refstepcounter{que}\theque.Describe the choice situation or good to be valued:** \newline 
    (see the \textbf{\hyperref[subsec-que-structure]{Questionnaire: Structure}} subsection for details)

-   **\refstepcounter{que}\theque. Which attributes (and respective levels) are you using?** \newline 
    (see the \textbf{\hyperref[subsec-que-structure]{Questionnaire: Structure}} subsection for details)
    
-   **\refstepcounter{que}\theque. List the number of alternatives per choice set, the number of choice sets in total and any blocks or random assignments if applicable.** \newline 
    The choice set consisted of one hypothetical alternative and one status quo alternative and five attributes with 5,2,5,3,10 levels. In the main study, we used a full factorial with random assignment.
    
-   **\refstepcounter{que}\theque. How did you code your attributes in the design? [eg. linear, dummy, effects]** \newline 
    In our experimental design we coded all attributes linearly except for visibility and accessibility which we coded with dummy variables.

-   **\refstepcounter{que}\theque. Which socio-demographic and other case-specific variables do you need to test your hypotheses? Did you integrate socio-demographic and other case-specific variables in the design process, and if yes how?** \newline 
    (see the \textbf{\hyperref[subsec-que-structure]{Questionnaire: Structure}} subsection for details)
    We need the actual status quo of respondents' places of residence (case-specific spatial variable) to estimate our envisioned models. However we did not include these variables in the design process.

-   **\refstepcounter{que}\theque. Which assumptions on the utility function (or other decision-making rules) did you use to generate the design? [e.g. Random utility maximization, random regret minimization etc.]** \newline 
    We assume that people choice according to random utility maximization.
    
-   **\refstepcounter{que}\theque. How did you create your experimental design? [orthogonal, eﬀicient, number of choice sets per person; labeled vs. unlabeled DCE etc.]** \newline 
     In the main study, we used a full factorial of $5*2*5*3*10=1500$ alternatives. For the first pre-test we used an efficient design created with the R package spdesign with 100 alternatives and 10 blocks. For the second pre-test, we used a larger efficient design with 500 choice sets and a random assignment of 10 out of these 500 choice sets for each respondent. 
    
-   **\refstepcounter{que}\theque. If eﬀicient design, which priors did you use, and how did you obtain them?** \newline 
    For the first pre-test priors were roughly based on the results from the focus groups. The second pre-test used priors from the models estimated in the first pre-test. 
    
-   **\refstepcounter{que}\theque. Did you test the design, e.g. with simulation (attach file)?** \newline 
    To control for potential design effects we simulated the results for our design with Monte-Carlo simulations in R. Since we assume that the respondents endowment is influencing their choices we incorporated it into the test of our designs. Therefore, we draw “fake” respondents weighted by population density and computed their individual endowments with protected areas and high nature value farmland as we do it in the survey.

-   **\refstepcounter{que}\theque. Do you use an additional split sample approach (between-subject design). If yes, did you integrate the split-sample in the design?** \newline 
    (see the \textbf{\hyperref[subsec-que-structure]{Questionnaire: Structure}} subsection for details)

-   **\refstepcounter{que}\theque. Do you randomize the order of choice sets and attributes?**\newline
    (see the \textbf{\hyperref[randoms]{Randomizations}} subsection for details)


-   **\refstepcounter{que}\theque. Do you use an opt-out option or a status quo?**\newline
    (see the \textbf{\hyperref[subsec-que-structure]{Questionnaire: Structure}} subsection for details)
    
-   **\refstepcounter{que}\theque. Anything else you want to mention regarding experimental design:**\newline
    (/)

-   **\refstepcounter{que}\theque. Which discrete choice models do you plan to estimate? Describe your model specification (e.g. utility function to be estimated)**\newline
    We think that for both attributes - protected area and high nature value farmland - the utility obtained from new areas depends on the individual endowment of the respondents. Therefore, we estimate models which allow for diminishing marginal utility or even negative marginal utility of those attributes depending on the respondent’s status quo. The different functional forms we want to consider are: Quadratic, Log, Log-Linear, Box-Cox and Linear (as baseline reference model). Additionally, we consider to estimate mixed forms of these models and to do model averaging. We will test for spatial autocorrelation and if necessary will either apply a spatial lag or spatial error model to account for it. We have outlined these specifications in the Appendix (Results from Pre-Tests and Soft Launch)

-   **\refstepcounter{que}\theque. Do you control for unobserved and observed heterogeneity, if yes, how (e.g. interactions, membership function in latent class model?**\newline
    We control for unobserved and observed heterogeneity in preferences by estimating mixed logit models and latent class logit models and testing interactions with socio-demographic and/or spatially varying variables.


-   **\refstepcounter{que}\theque. Do you estimate separate models for different groups?**\newline
    To test methodical hypotheses which allow for testing of split samples, we use the following approaches: 
    
    1. We compare frequencies of choices using non-parametric tests
    2. We estimate separate models for each split sample and compare estimated parameters and willingness to pay values with z-tests and Poe tests.
    3. We estimate a pooled model with interaction terms between the attributes and split sample dummies. 
    
  Which approach we will eventually report in a paper depends on the specific case. However, we will always carry out all three approaches and report them in an online appendix.

-   **\refstepcounter{que}\theque. If methodological research question, describe in detail how you test your methodical hypotheses**\newline
    (see the \textbf{\hyperref[estimation]{Estimation}} section for details)

-   **\refstepcounter{que}\theque. Describe any additional exploratory analysis you have planned to conduct.**\newline
    (/)

-   **\refstepcounter{que}\theque. Anything else you want to register regarding the design**\newline
    (/)

-   **\refstepcounter{que}\theque. **\newline
    (/)

-   **\refstepcounter{que}\theque. Do you use any measures to enhance validity and reduce hypothetical bias? (e.g. cheap talk, consequentiality, budget reminder, quiz questions)**\newline
    The potential influence of hypothetical bias is addressed by repeatedly emphasizing the possibility of implementation of an analogous approach to the presented hypothetical referendum in a real-world context. Additionally, respondents are regularly reminded that the results of the survey will be used to inform political decision-making, highlighting the potential influence their responses could have on actual policy outcomes. On each question set, an accompanying remark highlights the fact that respondents should vote in favor of the proposed measure only if they themselves are willing to pay the specified amount for the given period of time.
    
-   **\refstepcounter{que}\theque. Which follow up questions do you use?**\newline
    (see the \textbf{\hyperref[subsec-que-structure]{Questionnaire: Structure}} subsection for details)
    
-   **\refstepcounter{que}\theque. What Inference criteria do you use (e.g. z-test 5% level)**\newline
    To test for differences, we use appropriate tests, depending on the distribution of the variables. As the general threshold, we use a 5 % significance level.  In most cases, we use z-tests (for example, to test for differences in estimated parameters in logit models). For hypotheses, where we estimate separate models, we may also use the Poe test to test for differences in ratios of parameters (such as WTP). 
    
-   **\refstepcounter{que}\theque. Define how you deal with outliers and how you exclude respondents/choices. **\newline
    (see the \textbf{\hyperref[estimation]{Estimation}} section for details)
    
-   **\refstepcounter{que}\theque. Anything else you want to preregister?**\newline
    (/)
    
    
# References {.unnumbered}

::: {#refs}
:::    